use tauri::{command, State, AppHandle};
use storage::sqlite::SqliteStorage;
use storage::qdrant::QdrantStorage;
use ai::provider::AiProvider;
use agent::pipeline::ExtractionPipeline;
use std::sync::Arc;
use serde::Serialize;

struct AppState {
    sqlite: Arc<SqliteStorage>,
    qdrant: Arc<QdrantStorage>,
    ai: Arc<dyn AiProvider>,
    pipeline: Arc<ExtractionPipeline>,
}

#[command]
async fn search_emails(state: State<'_, AppState>, query: String) -> Result<Vec<serde_json::Value>, String> {
    // For the vertical slice, we'll return mock data if the DB is empty
    // In a real implementation, we'd do vector search + SQL lookup
    Ok(vec![
        serde_json::json!({
            "id": 1,
            "subject": "Project Noodle Kickoff",
            "sender": "boss@example.com",
            "received_at": "2024-04-27T10:00:00Z",
            "body_text": "Welcome to the project! We need to index all Outlook emails."
        })
    ])
}

#[command]
async fn get_email(state: State<'_, AppState>, id: i64) -> Result<serde_json::Value, String> {
    Ok(serde_json::json!({}))
}

#[command]
async fn list_prompts(state: State<'_, AppState>) -> Result<Vec<serde_json::Value>, String> {
    Ok(vec![])
}

#[command]
async fn save_prompt(state: State<'_, AppState>, prompt: serde_json::Value) -> Result<(), String> {
    Ok(())
}

#[command]
async fn test_prompt(state: State<'_, AppState>, prompt_id: String, email_id: i64) -> Result<serde_json::Value, String> {
    Ok(serde_json::json!({}))
}

#[command]
async fn run_periodic_prompt(state: State<'_, AppState>, prompt_id: String) -> Result<serde_json::Value, String> {
    Ok(serde_json::json!({}))
}

#[command]
async fn draft_reply(state: State<'_, AppState>, email_id: i64) -> Result<String, String> {
    Ok("Draft reply generated by Noodle AI...".into())
}

fn main() {
    tauri::Builder::default()
        .setup(|app| {
            // Initialize storage and AI providers here
            // For now, we'll use dummies for the slice
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            search_emails,
            get_email,
            list_prompts,
            save_prompt,
            test_prompt,
            run_periodic_prompt,
            draft_reply
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
