use agent::pipeline::ExtractionPipeline;
use ai::provider::AiProvider;
use serde::Serialize;
use std::sync::Arc;
use storage::qdrant::QdrantStorage;
use storage::sqlite::SqliteStorage;
use tauri::{command, AppHandle, State};

struct AppState {
    sqlite: Arc<SqliteStorage>,
    qdrant: Arc<QdrantStorage>,
    ai: Arc<dyn AiProvider>,
    pipeline: Arc<ExtractionPipeline>,
}

#[command]
async fn search_emails(
    _state: State<'_, AppState>,
    _query: String,
) -> Result<Vec<serde_json::Value>, String> {
    // For the vertical slice, we'll return mock data if the DB is empty
    // In a real implementation, we'd do vector search + SQL lookup
    Ok(vec![serde_json::json!({
        "id": 1,
        "subject": "Project Noodle Kickoff",
        "sender": "boss@example.com",
        "received_at": "2024-04-27T10:00:00Z",
        "body_text": "Welcome to the project! We need to index all Outlook emails."
    })])
}

#[command]
async fn get_email(_state: State<'_, AppState>, _id: i64) -> Result<serde_json::Value, String> {
    Ok(serde_json::json!({}))
}

#[command]
async fn list_prompts(_state: State<'_, AppState>) -> Result<Vec<serde_json::Value>, String> {
    Ok(vec![])
}

#[command]
async fn save_prompt(
    _state: State<'_, AppState>,
    _prompt: serde_json::Value,
) -> Result<(), String> {
    Ok(())
}

#[command]
async fn test_prompt(
    _state: State<'_, AppState>,
    _prompt_id: String,
    _email_id: i64,
) -> Result<serde_json::Value, String> {
    Ok(serde_json::json!({}))
}

#[command]
async fn run_periodic_prompt(
    _state: State<'_, AppState>,
    _prompt_id: String,
) -> Result<serde_json::Value, String> {
    Ok(serde_json::json!({}))
}

#[command]
async fn draft_reply(_state: State<'_, AppState>, _email_id: i64) -> Result<String, String> {
    Ok("Draft reply generated by Noodle AI...".into())
}

fn main() {
    tauri::Builder::default()
        .setup(|app| {
            // Initialize storage and AI providers here
            // For now, we'll use dummies for the slice
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            search_emails,
            get_email,
            list_prompts,
            save_prompt,
            test_prompt,
            run_periodic_prompt,
            draft_reply
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
